### ISSUE TITLE
Decoding messages for single core multi-threaded  nexus trace messages.

### ISSUE THREAD

**Issue by ankeshanand2405** [sifive/trace-decoder#27]
Hi,
Does the trace decoder decode single-core multi-threaded nexus trace messages?
Thanks,
Ankesh

**Comment by bradseevers** [comment]
The decoder has no knowledge of threads. It will faithfully decode the instructions executed on a single-core (or multi-core), but does not reconstruct execution by thread. Is that what you were asking?
