### ISSUE TITLE
Couldn't decode 64 bits PCs having non-zero value in top bits. 

### ISSUE THREAD

**Issue by ankeshanand2405** [sifive/trace-decoder#28]
Hi,
I encounter a scenario where the first synchronous message(out of debug mode) having PC (64'h7fffff000000d234) is not decoded correctly. What can be the issue?
Thanks,
Ankesh

**Comment by bradseevers** [comment]
I have decoded many 64 bit decodes with no issues. Can you provide information about the type of core you are collecting the trace on? If you provide a trace file and an elf file, I will try it. Also, if your system is not a single core, you must specify the number of source bits in the trace messages (with the -srcbits flag) for messages to be decoded correctly.

**Comment by ankeshanand2405** [comment]
The trace file (trace_msg.rtd) contains messages for only first synchronous message. The synchronous message contains these informations:
1 bit right Shifted PC:  7ffffff00005a2fd
Type:  Synchronous message(exit from debug mode) -- TCODE= 9, SYNC=3
ICOUNT = 0
The system is single-core.
Please find the attached file containing both *rtd and *elf file:
[trace_log_and_elf.zip](https://github.com/sifive/trace-decoder/files/9581523/trace_log_and_elf.zip)

I was getting this error while decoding.
Info: SliceFileParser::readBinaryMsg(): Skipping: 32
Info: SliceFileParser::readBinaryMsg(): Skipping: 63
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
unsupported data write with sync trace message
Error possibly due to corrupted first message in trace - skipping message
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 63
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 63
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 63
Info: SliceFileParser::readBinaryMsg(): Skipping: 0a
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 31
Info: SliceFileParser::readBinaryMsg(): Skipping: 66
Info: SliceFileParser::readBinaryMsg(): Skipping: 0a
End of Trace File

**Comment by bradseevers** [comment]
Sorry I didn't get back to you sooner, but I have been on vacation.

I took a look at the files you sent. The file trace_msg.rtd is not a valid
trace file. It is a text file and not a binary file. Trace files must be in
binary format. Did you create this file by hand? It has the text contents:

2cf40d24
00000468
fcfcfcfc
ffffff1f

Let me know if you have any questions.

-brad

**Comment by ankeshanand2405** [comment]
Sorry I couldn't provide the correct bin and elf at that time. Can you please test with these attachments?
[Trace_rtd_and_elf.zip](https://github.com/sifive/trace-decoder/files/10968907/Trace_rtd_and_elf.zip)

**Comment by bradseevers** [comment]
The 64 bit pc bug was fixed in Feb. If you get a new version of the trace
decoder, it will have the fix.

The example you provided has a very large elf file (over 14MB). The trace
decoder uses objdump to disassemble the elf, and then parses the output.
This may have revealed another issue with the trace decoder which I will
investigate. When I attempt to decode your example, it never seems to
finish the objdump process, or it is taking a very long time.

I recommend you get a new copy of the trace decoder and create a smaller
example to verify it is decoding correctly for you. Please let me know if
you see any other issues.

Thanks,

-brad

**Comment by ankeshanand2405** [comment]
Thanks for your response.
I tried with the new version of thee trace decoder.
On using it with a smaller elf and rtd, it throws this error.
![image](https://user-images.githubusercontent.com/69339699/225524076-d4d92b47-a43a-4927-b88c-59d87ea948b5.png)

**Comment by bradseevers** [comment]
If you can send me a link to the rtd and elf files, I will check it out.

-brad

**Comment by ankeshanand2405** [comment]
Yes Sure, Here I am attaching both elf and RTD files.
[demo_sifive.zip](https://github.com/sifive/trace-decoder/files/10990139/demo_sifive.zip)

**Comment by bradseevers** [comment]
What is odd is you are not getting additional error messages explaining
what went wrong. I just updated the trace-decoder source on github to
include some additional error information. Go ahead and grab and build it
and let me know what you see.

-brad

**Comment by ankeshanand2405** [comment]
Here is what I got:
![image](https://user-images.githubusercontent.com/69339699/225993541-36a2aead-d98b-4505-bb42-7ca177e88e4d.png)

It's failing in this section of code:
![image](https://user-images.githubusercontent.com/69339699/225993256-1c9728f2-31de-40d1-90ab-2427fe81d2c9.png)

**Comment by bradseevers** [comment]
Okay - I added more error messages, and may have found and fixed the issue
you are having. It is checked into github; give it a try!

**Comment by ankeshanand2405** [comment]
I am getting this fail message now:
![image](https://user-images.githubusercontent.com/69339699/226071476-d09f646a-1555-4a7e-b95c-1183582f49fa.png)

**Comment by bradseevers** [comment]
This is really odd, for a couple of reasons.

- I do not get this error, but instead everything runs fine.
- There are no error exits from parseNLSStrings() that don't print some
additional error messages.

This makes me suspect the problem is something in your build or execution
environment.

I will work on a version with additional debug information and place it in
a branch for the trace decoder and let you know.

-brad

**Comment by bradseevers** [comment]
I created a branch to the trace decoder github repo. It is nls-issue. Clone
the latest trace-decoder repo, check out the nls-issue branch, build it,
and try that. It contains some extra output that should help us see what is
going on.

-brad

**Comment by ankeshanand2405** [comment]
Hi Brad, Sorry for the late reply. I am able to decode trace messages now. I made some mistakes while taking the changes to the files.
Thanks for your support. 
I'll try to decode PCs with upper bits set and will get back to you. Although I also tried with large sized elf, it is taking endless time to disassemble elf as you mentioned earlier.

**Comment by bradseevers** [comment]
Great!

Yes, I expect there is an issue with the large elf file. I will take a look
soon.

-brad

**Comment by ankeshanand2405** [comment]
Hi Brad, I tested with the 64 bit PCs having upper bits non-zero and smaller elfs. Decoder is decoding correctly for it.
Have you had a chance to debug the decoder for the larger ELF files?

**Comment by bradseevers** [comment]
Sorry, I have been very busy lately and have not had a chance to look at
the large elf file issue. It is on my list.

Just curious, where do you work?

Thanks,

-brad

**Comment by ankeshanand2405** [comment]
Hi Brad, I am working in an AI/ML startup in stealth mode.

**Comment by ankeshanand2405** [comment]
Hi Brad, Did you get a chance to look into the larger elf file decoding issue?

**Comment by bradseevers** [comment]
I tried using the latest trace decoder built from the master branch. It
does not hang.But the decode looks like it is a bad rtd file
(c300_trace_msg.rtd). I get the following output when decoded using the
command: dqr -t c300_trace_msg.rtd -e vmlinux_4_19.elf -od
/path/to/objdump/riscv64-unknown-elf-objdump -trace -debug. The trace
starts out at address ffffffe0005ee9ea (a virtual address), which looks
good, but switches to address 40000004, which is not part of the elf file.
That may be okay - it may be switching to openSBI, which is its own
separate executable (this happens with exceptions, and message #2 says it
had an exception). The decoder can't get the instructions at 0x40000004, so
it looks for the next sync-type message, skipping everything until it finds
one. It never finds one, so it never actually decodes any instructions.

The decoder will handle the openSBI decode, IF the core you are using
supports generating the trace ownership messages in the trace encoder. They
provide privilege level information (U, S, and M mode) so the decoder knows
what code to disassemble based on mode. Also, you need to have a binary
image of the openSBI code for your system.

Trace decoder output:

Raw Message # 1: 24 0d d4 4c dc 2c 00 00 fc fc fc fc 1f
Trace: Msg # 1, NxtAddr: ffffffe0005ee9ea, TCode: SYNC (9) Reason: (3) Exit
Debug I-CNT: 0 F-Addr: 0x7ffffff0002f74f5
NextInstruction(): counts are exhausted, core: 0
Raw Message # 2: 10 05 dc 4c dc 2c 80 00 fc fc fc fc 1f

Trace: Msg # 2, NxtAddr: 40000004, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x7ffffff0202f74f7
Error: getInstructionByAddress failed. core: 0, pid: 0, addr: 0x40000004 -
looking for next sync message
Debug: resetTrace(0)
Raw Message # 3: 0c 43

Trace: Msg # 3, NxtAddr: 40000004, TCode: DIRECT BRANCH (3) I-CNT: 16
Raw Message # 4: 10 05 03

Trace: Msg # 4, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 5: 10 05 03

Trace: Msg # 5, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 6: 10 05 03

Trace: Msg # 6, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 7: 10 05 03

Trace: Msg # 7, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 8: 10 05 03

Trace: Msg # 8, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 9: 10 04 05 dc 4c dc 2c 80 00 fc fc fc fc 1f

Trace: Msg # 9, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 16 U-ADDR: 0x7ffffff0202f74f7
Raw Message # 10: 10 05 dc 4c dc 2c 80 00 fc fc fc fc 1f

Trace: Msg # 10, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x7ffffff0202f74f7
Raw Message # 11: 10 e5 03

Trace: Msg # 11, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 14 U-ADDR: 0x00000000
Raw Message # 12: 10 05 03

Trace: Msg # 12, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 13: 10 05 03

Trace: Msg # 13, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 14: 10 05 03

Trace: Msg # 14, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 15: 10 05 03

Trace: Msg # 15, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 16: 10 05 03

Trace: Msg # 16, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 17: 10 05 03

Trace: Msg # 17, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 18: 10 05 03

Trace: Msg # 18, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 19: 10 05 03

Trace: Msg # 19, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 20: 10 05 03

Trace: Msg # 20, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 21: 10 05 03

Trace: Msg # 21, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 22: 10 05 03

Trace: Msg # 22, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 23: 10 05 03

Trace: Msg # 23, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 24: 10 05 03

Trace: Msg # 24, NxtAddr: 00000000, TCode: INDIRECT BRANCH (4) Branch Type:
Exception (1) I-CNT: 0 U-ADDR: 0x00000000
Raw Message # 25: 10 05 03
